### ISSUE TITLE
Communication Error

### ISSUE THREAD

**Issue by JPLanh** [JPLanh/DistributedFileSystem#1]
Error trying to retrieve the chord from another computer, displaying this message, even though it was able to locate the URI

Traceback (most recent call last):
  File "C:\Users\KengPeng\Desktop\Python\DistFileSys\Client.py", line 148, in <module>
    prompt(chord)
  File "C:\Users\KengPeng\Desktop\Python\DistFileSys\Client.py", line 123, in prompt
    chord.joinRing(IPGet, int(m.hexdigest(), 16))
  File "C:\Users\KengPeng\Desktop\Python\DistFileSys\Chord.py", line 143, in joinRing
    chordGet._pyroBind()
  File "C:\Users\KengPeng\AppData\Local\Programs\Python\Python36-32\lib\site-packages\Pyro4\core.py", line 408, in _pyroBind
    return self.__pyroCreateConnection(True)
  File "C:\Users\KengPeng\AppData\Local\Programs\Python\Python36-32\lib\site-packages\Pyro4\core.py", line 596, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "C:\Users\KengPeng\AppData\Local\Programs\Python\Python36-32\lib\site-packages\Pyro4\core.py", line 562, in connect_and_handshake
    raise errors.CommunicationError(error)
Pyro4.errors.CommunicationError: connection to ('192.168.1.126', 9090) rejected: unknown object
>>>

**Comment by JPLanh** [comment]
The URI 
PYRO:obj_3b2844cdb2b243b981fbbe2df457f9f4@192.168.1.126:9090

**Comment by JPLanh** [comment]
slight progress where I am able to establish communication with another computer after i change the port of locating the name server to 9090 and change the port of the chord to something else.. I'm assuming that because the port was the same, the other chord was trying to access the nameserver and not the chord.

**Comment by JPLanh** [comment]
Changed it around where I no longer need to start up a name server from the command line, instead it will be executed in the server file with the port being 1 less than the desired port.
For example: `localhost:23245`
will result in starting up a namespace of localhost:23244, and the chord located in localhost:23245

**Comment by JPLanh** [comment]
It is to be aware as well that communicating between two different computer, they can not be under localhost, but as their IP.
