### ISSUE TITLE
Migrate to GCP from AWS

### ISSUE THREAD

**Issue by JPLanh** [JPLanh/DistributedFileSystem#19]
After transferring the server onto the GCP, the servers no longer communicate each other. Seem like there has been issue with having the nameserver set as the external IP. It currently work as setting the nameserver ip as the internal IP, and have other connect with the external IP (well make sense), however when a client connect to the server, the client ends up using the internal IP which is causing an error. Might have to look at the code on what the chord instance get while the code executes.

**Comment by JPLanh** [comment]
Traceback (most recent call last):
  File "C:\Users\JPLan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Pyro4\core.py", line 515, in connect_and_handshake
    sslContext=sslContext)
  File "C:\Users\JPLan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Pyro4\socketutil.py", line 307, in createSocket
    sock.connect(connect)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JPLan\Desktop\Pyro4_DistributedFileSystem-master\Client.py", line 269, in <module>
    ctypes.windll.kernel32.SetConsoleTitleW(str(chord.ip) + ":" + str(chord.port) + " (" + str(chord.guid) + ")")
  File "C:\Users\JPLan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Pyro4\core.py", line 275, in __getattr__
    self._pyroGetMetadata()
  File "C:\Users\JPLan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Pyro4\core.py", line 615, in _pyroGetMetadata
    self.__pyroCreateConnection()
  File "C:\Users\JPLan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Pyro4\core.py", line 596, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "C:\Users\JPLan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Pyro4\core.py", line 549, in connect_and_handshake
    raise ce
Pyro4.errors.CommunicationError: cannot connect to ('10.168.0.4', 26842): [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by JPLanh** [comment]
Pyro4 documentation states

> All Pyro daemons bind on localhost by default. This is because of security reasons. This means only processes on the same machine have access to your Pyro objects. If you want to make them available for remote machines, you’ll have to tell Pyro on what network interface address it must bind the daemon. This also extends to the built in servers such as the name server.

> Warning Read chapter Security before exposing Pyro objects to remote machines!
There are a few ways to tell Pyro what network address it needs to use. You can set a global config item HOST, or pass a host parameter to the constructor of a Daemon, or use a command line argument if you’re dealing with the name server. For more details, refer to the chapters in this manual about the relevant Pyro components.

> Pyro provides a couple of utility functions to help you with finding the appropriate IP address to bind your servers on if you want to make them publicly accessible:

> Pyro4.socketutil.getIpAddress()
> Pyro4.socketutil.getInterfaceAddress()

I have not occur this issue before with the AWS, and had it working. Seem like i have to have the server know it's internal and external IP.

**Comment by JPLanh** [comment]
Turns out google cloud platform does not allow the usage of RMI. This project will continue on from amazon aws
